#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/unison

cd ${0%/*}
if ps -ef | grep -v grep | grep importd.php ; then
	echo Import Daemon Already Running! Exiting!
        exit 0
else
	echo Starting Import Daemon...
        php ../daemon/importd.php -v >> ../log/importd.log &
        exit 0
fi
