#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/unison:/opt/mssql-tools/bin/

SQL_SVR="[server]"
SQL_DB="[database]"
SQL_USER="[user]"
SQL_PASS="[password]"
WIFIDB_INSTANCE="[node]"

cd ${0%/*}

ROW=$(sqlcmd -S $SQL_SVR -U $SQL_USER -P $SQL_PASS -d $SQL_DB -Q "SET NOCOUNT ON; SELECT COUNT(1) FROM settings WHERE node_name = '$WIFIDB_INSTANCE' AND daemon_state = 1")
daemonstate=`echo $ROW | sed 's/[\._-]//g' | sed 's/ //g'`

echo "Daemon State: $daemonstate"
if [ $daemonstate -ge 1 ]; then
	DATE_WITH_TIME=`date -u "+%Y-%m-%d %H:%M:%S"`
	ROW=$(sqlcmd -S $SQL_SVR -U $SQL_USER -P $SQL_PASS -d $SQL_DB -Q "SET NOCOUNT ON; SELECT COUNT(1) FROM schedule WHERE daemon = 'Import' AND status <> 'Running' AND enabled = 1 And nextrun <= '$DATE_WITH_TIME'")
	runcount=`echo $ROW | sed 's/[\._-]//g' | sed 's/ //g'`

	echo "[$DATE_WITH_TIME] $runcount processes needed."
	if [ $runcount -ge 1 ]; then

	  for (( c=1; c<=$runcount; c++ ))
	  do
		  echo "executing processes $c"
		  timestamp=$(date +%s)
		  logfile=importd_${timestamp}_${c}.log
		  php ../daemon/importd.php -o -v --logfile="${logfile}" > ../log/import/${logfile} &
		  sleep 1s
	  done
	fi
fi
echo "Cleaning up old logs..."
find ../log/import/ -mtime +1 -type f -delete

echo "Done. Exiting."
exit 0
