#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/unison

cd ${0%/*}
if ps -ef | grep -v grep | grep statsd.php ; then
	echo StatsD Daemon Already Running! Exiting!
else
	echo Starting StatsD Daemon...
	timestamp=$(date +%s)
	php ../daemon/statsd.php -o -v > ../log/statsd/statsd${timestamp}.log &
fi

echo "Cleaning up old logs..."
find ../log/statsd/ -mtime +1 -type f -delete

echo "Done. Exiting."
exit 0
