#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/unison

cd ${0%/*}
if ps -ef | grep -v grep | grep mltd.php ; then
    echo MLT Tile Daemon Already Running! Exiting!
else
    echo Starting MLT Tile Daemon...
        timestamp=$(date +%s)
        php ../daemon/mltd.php > ../log/mvt/mltd_${timestamp}.log &
fi

echo "Cleaning up old logs..."
find ../log/mvt/ -mtime +7 -type f -delete

echo "Done. Exiting."
exit 0
