#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/unison

cd ${0%/*}
if ps -ef | grep -v grep | grep mvtd.php ; then
    echo MVT Tile Daemon Already Running! Exiting!
else
    echo Starting MVT Tile Daemon...
        timestamp=$(date +%s)
        php ../daemon/mvtd.php > ../log/mvt/mvtd_${timestamp}.log &
fi

echo "Cleaning up old logs..."
find ../log/mvt/ -mtime +7 -type f -delete

echo "Done. Exiting."
exit 0
