#!/bin/bash
# Start/stop WiFiDB server instance
# WiFiDB v0.30v Build 1.
#
# create as: /etc/init.d/wifidb
# to activate it, run: chkconfig -add wifidb

### BEGIN INIT INFO
# Provides: wifidb daemon
# Required-Start: mysql
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start/stop wifidb server instance
### END INIT INFO

# Some things that run always
touch /var/lock/wifidb

wifidbpath="/opt/wifidb-0-30/tools/daemon"
pid_imp_expd="/var/run/wifidb/imp_expd.pid"
pid_geonamed="/var/run/wifidb/geonamed.pid"
pid_monitord="/var/run/wifidb/monitord.pid"

cd ${wifidbpath}

# Carry out specific functions when asked to by the system
case "$1" in
  start)
	prog="Import Export Daemon"
    if [ -f $pid_imp_expd ]
    then
		# failed
		echo "$prog is already running..."
    else
		echo "Starting $prog"
		php ${wifidbpath}/rund.php start ied
        if [ -f $pid_imp_expd ]
        then
			# success
            echo "$prog started..."
        else
			# failed
			echo "$prog failed to start..."
        fi
	fi
	
	prog="Geoname Daemon"
    if [ -f $pid_geonamed ]
    then
		# failed
		echo "$prog is already running..."
    else
		echo "Starting $prog"
		php ${wifidbpath}/rund.php start geo
        if [ -f $pid_geonamed ]
        then
			# success
            echo "$prog started..."
        else
			# failed
			echo "$prog failed to start..."
        fi
	fi
	
	prog="Monitor Daemon"
    if [ -f $pid_monitord ]
    then
		# failed
		echo "$prog is already running..."
    else
		echo "Starting $prog"
		php ${wifidbpath}/rund.php start mon
        if [ -f $pid_monitord ]
        then
			# success
            echo "$prog started..."
        else
			# failed
			echo "$prog failed to start..."
        fi
	fi
    ;;
  stop)
	prog="Import Export Daemon"
    echo $"Stopping $prog: "
    php ${wifidbpath}/rund.php stop ied
	if [ -f $pid_imp_expd ]
	then
        # failed
        echo "$pid_imp_expd still exists. $prog was not stopped properly..."
    else
        # success
        echo "$prog stopped..."
    fi
	
	prog="Geoname Daemon"
    echo $"Stopping $prog: "
    php ${wifidbpath}/rund.php stop geo
	if [ -f $pid_geonamed ]
	then
        # failed
        echo "$pid_geonamed still exists. $prog was not stopped properly..."
    else
        # success
        echo "$prog stopped..."
    fi
	
	prog="Monitor Daemon"
	#sleep so monitor daemon can get state before shutting down
	sleep 30
    echo $"Stopping $prog: "
    php ${wifidbpath}/rund.php stop mon
	if [ -f $pid_monitord ]
	then
        # failed
        echo "$pid_monitord still exists. $prog was not stopped properly..."
    else
        # success
        echo "$prog stopped..."
    fi
    ;;
  restart)
   /etc/init.d/wifidb stop
   /etc/init.d/wifidb start
    ;;
  status)
    php ${wifidbpath}/rund.php status ied
    php ${wifidbpath}/rund.php status mon
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
