#!/usr/bin/env python3
"""Generate blank_db.pgsql from blank_db.sqlsrv.

The MSSQL script is the source of truth for the WifiDB schema, so the Postgres
schema is derived from it mechanically rather than hand-transcribed. Identifiers
keep their exact MSSQL case and are double-quoted, because the PHP layer indexes
result rows by those names (e.g. $row['GPS_ID'], $row['Country']) and Postgres
would otherwise fold them to lowercase.
"""
import re
import sys
from collections import Counter, OrderedDict

SRC = sys.argv[1] if len(sys.argv) > 1 else 'blank_db.sqlsrv'
DST = sys.argv[2] if len(sys.argv) > 2 else 'blank_db.pgsql'

src = open(SRC, encoding='utf-8-sig', errors='replace').read()


def q(name):
    return '"%s"' % name.replace('"', '""')


# ---------------------------------------------------------------- type mapping
def map_type(sqltype, ident_start):
    t = sqltype.strip()
    m = re.match(r'\[(\w+)\](?:\s*\(([^)]*)\))?', t)
    base, arg = m.group(1).lower(), (m.group(2) or '').strip()

    if ident_start is not None:
        # GENERATED BY DEFAULT (not ALWAYS) so the seed rows can supply explicit
        # ids, the same way SET IDENTITY_INSERT does on MSSQL.
        kind = 'bigint' if base == 'bigint' else 'integer'
        start = ' (START WITH %s)' % ident_start if ident_start != '1' else ''
        return '%s GENERATED BY DEFAULT AS IDENTITY%s' % (kind, start)

    if base in ('nvarchar', 'varchar', 'nchar', 'char'):
        if arg.lower() == 'max':
            return 'text'
        return ('varchar(%s)' % arg) if base in ('nvarchar', 'varchar') else 'char(%s)' % arg
    if base in ('int',):
        return 'integer'
    if base in ('bigint', 'smallint'):
        return base
    if base == 'tinyint':
        return 'smallint'
    if base == 'bit':
        # smallint, not boolean: the PHP layer binds plain 0/1 integers to these
        # columns and Postgres will not coerce an integer to boolean.
        return 'smallint'
    if base == 'datetime':
        return 'timestamp'
    if base == 'datetime2':
        return 'timestamp(%s)' % arg if arg else 'timestamp'
    if base in ('decimal', 'numeric'):
        return 'numeric(%s)' % re.sub(r',\s*', ', ', arg)
    if base == 'varbinary':
        return 'bytea'
    if base == 'float':
        return 'double precision'
    raise SystemExit('unmapped type: %s' % t)


# ---------------------------------------------------------------- defaults
defaults = {}
for m in re.finditer(
        r'^ALTER TABLE \[dbo\]\.\[([^\]]+)\] ADD\s+(?:CONSTRAINT \[[^\]]+\]\s+)?DEFAULT \((.*?)\) FOR \[([^\]]+)\]',
        src, re.M):
    table, expr, col = m.group(1), m.group(2).strip(), m.group(3)
    if expr.upper() == 'NULL':
        continue  # Postgres columns already default to NULL
    if expr.lower() == 'getdate()':
        expr = 'CURRENT_TIMESTAMP'
    elif re.fullmatch(r'\(-?\d+\)', expr):
        expr = expr[1:-1]
    elif expr.startswith("N'"):
        expr = expr[1:]
    defaults[(table, col)] = expr


# ---------------------------------------------------------------- tables
def parse_key_cols(block):
    return [(mm.group(1), mm.group(2)) for mm in
            re.finditer(r'\[([^\]]+)\]\s+(ASC|DESC)', block)]


tables = OrderedDict()
for m in re.finditer(r'CREATE TABLE \[dbo\]\.\[([^\]]+)\]\((.*?)\n\)\s*ON \[PRIMARY\]', src, re.S):
    table, body = m.group(1), m.group(2)
    cols, constraints = [], []

    # Column lines start at the beginning of a line with a tab + [name].
    for line in body.split('\n'):
        cm = re.match(r'^\t\[([^\]]+)\] (\[\w+\](?:\s*\([^)]*\))?)(?: IDENTITY\((\d+),\s*\d+\))?'
                      r'( NOT NULL| NULL)?,?\s*$', line)
        if not cm:
            continue
        name, rawtype, ident, nullable = cm.group(1), cm.group(2), cm.group(3), cm.group(4)
        piece = '    %s %s' % (q(name), map_type(rawtype, ident))
        dflt = defaults.get((table, name))
        if dflt:
            piece += ' DEFAULT %s' % dflt
        if nullable and nullable.strip() == 'NOT NULL':
            piece += ' NOT NULL'
        cols.append(piece)

    # admin_jobs declares its PK inline with no CONSTRAINT name, so the name is
    # optional here and synthesised when absent.
    for cm in re.finditer(r'(?:CONSTRAINT \[([^\]]+)\] )?(PRIMARY KEY|UNIQUE) (?:CLUSTERED|NONCLUSTERED)\s*\((.*?)\)WITH',
                          body, re.S):
        cname, kind, keys = cm.group(1), cm.group(2), cm.group(3)
        if not cname:
            cname = 'PK_%s' % table if kind == 'PRIMARY KEY' else 'UQ_%s' % table
        keycols = ', '.join(q(c) for c, _ in parse_key_cols(keys))
        constraints.append('    CONSTRAINT %s %s (%s)' % (q(cname), kind, keycols))

    tables[table] = cols + constraints


# ---------------------------------------------------------------- indexes
idx_re = re.compile(
    r'CREATE (UNIQUE )?NONCLUSTERED INDEX \[([^\]]+)\] ON \[dbo\]\.\[([^\]]+)\]\s*'
    r'\((.*?)\)\s*(?:INCLUDE\((.*?)\)\s*)?(?:WHERE \((.*?)\)\s*)?WITH \(PAD_INDEX', re.S)

raw_indexes = []
for m in idx_re.finditer(src):
    raw_indexes.append({
        'unique': bool(m.group(1)),
        'name': m.group(2),
        'table': m.group(3),
        'keys': parse_key_cols(m.group(4)),
        'include': re.findall(r'\[([^\]]+)\]', m.group(5) or ''),
        'where': m.group(6),
    })

# MSSQL index names are scoped per table; Postgres index names are schema-global,
# so disambiguate the ones that repeat (id, File_ID, IX_MSREC3, IX_File_ID).
dupes = {n for n, c in Counter(i['name'] for i in raw_indexes).items() if c > 1}
for i in raw_indexes:
    i['pgname'] = ('%s_%s' % (i['table'], i['name'])) if i['name'] in dupes else i['name']


def render_where(expr):
    # [points] IS NOT NULL AND [HighGps_ID] IS NOT NULL -> quoted identifiers
    return re.sub(r'\[([^\]]+)\]', lambda mm: q(mm.group(1)), expr).strip()


# ---------------------------------------------------------------- output
out = []
w = out.append

w('--')
w('-- WifiDB blank database -- PostgreSQL')
w('--')
w('-- Generated from blank_db.sqlsrv (the MSSQL schema is the source of truth).')
w('--')
w('-- All identifiers are double-quoted so they keep the exact case used by the')
w('-- MySQL/MSSQL schemas. The PHP layer reads result rows by those names')
w("-- ($row['GPS_ID'], $row['Country'], ...), and unquoted identifiers would be")
w('-- folded to lower case by Postgres and break every one of those lookups.')
w('-- Queries in the pgsql branches must quote identifiers the same way.')
w('--')
w('-- Usage:  createdb wifi && psql -d wifi -f blank_db.pgsql')
w('--')
w('')
w('BEGIN;')
w('')
w('SET client_encoding = \'UTF8\';')
w('SET standard_conforming_strings = on;')
w('')

for table, parts in tables.items():
    w('CREATE TABLE %s (' % q(table))
    w(',\n'.join(parts))
    w(');')
    w('')

w('--')
w('-- Indexes')
w('--')
w('')
for i in raw_indexes:
    keys = ', '.join('%s%s' % (q(c), '' if d == 'ASC' else ' DESC') for c, d in i['keys'])
    stmt = 'CREATE %sINDEX %s ON %s (%s)' % (
        'UNIQUE ' if i['unique'] else '', q(i['pgname']), q(i['table']), keys)
    if i['include']:
        stmt += ' INCLUDE (%s)' % ', '.join(q(c) for c in i['include'])
    if i['where']:
        stmt += ' WHERE %s' % render_where(i['where'])
    w(stmt + ';')
w('')

w('--')
w('-- Foreign keys')
w('--')
w('')
for m in re.finditer(
        r'ALTER TABLE \[dbo\]\.\[([^\]]+)\]\s+WITH CHECK ADD\s+CONSTRAINT \[([^\]]+)\] '
        r'FOREIGN KEY\(\[([^\]]+)\]\)\s*\nREFERENCES \[dbo\]\.\[([^\]]+)\] \(\[([^\]]+)\]\)', src):
    w('ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s);' % (
        q(m.group(1)), q(m.group(2)), q(m.group(3)), q(m.group(4)), q(m.group(5))))
w('')

# ---------------------------------------------------------------- seed data
w('--')
w('-- Seed data')
w('--')
w('')

seeded = []
for m in re.finditer(r'^INSERT \[dbo\]\.\[([^\]]+)\] \((.*?)\) VALUES \((.*)\)\s*$', src, re.M):
    table, collist, values = m.group(1), m.group(2), m.group(3)
    if table not in seeded:
        seeded.append(table)
    cols = ', '.join(q(c) for c in re.findall(r'\[([^\]]+)\]', collist))
    vals = re.sub(r'\bCAST\(N?(\'(?:[^\']|\'\')*\') AS DateTime2?\)', r'CAST(\1 AS timestamp)', values)
    vals = re.sub(r"\bN('(?:[^']|'')*')", r'\1', vals)
    w('INSERT INTO %s (%s) VALUES (%s);' % (q(table), cols, vals))
w('')

w('--')
w('-- Re-sync the identity sequences past the seeded rows')
w('--')
w('')
for table in seeded:
    idcol = 'carrier_id' if table == 'cell_carriers' else 'id'
    w("SELECT setval(pg_get_serial_sequence('%s', '%s'), "
      '(SELECT MAX(%s) FROM %s));' % (q(table).replace('"', '\\"') if False else table,
                                      idcol, q(idcol), q(table)))
w('')
w('COMMIT;')
w('')

open(DST, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print('wrote %s: %d tables, %d indexes, %d seed rows' % (
    DST, len(tables), len(raw_indexes), len(re.findall(r'^INSERT \[dbo\]', src, re.M))))
